### ISSUE TITLE
Update API call shall utilize aadmURI and rmURI parameters of saveTOSCA API call in the Semantic Reasoner

### ISSUE THREAD

**Issue by kmlTE** [SODALITE-EU/platform-discovery-service#17]
# Current state
PDS does not have an option to re-save the models into the specific aadmURI and rmURI. This causes unnecessary duplicate population of AADM and RM models in the KB.

# Desired state
When aadmURI and rmURI are provided in the /update request, PDS updates these particular models

**Comment by alexmaslenn** [comment]
fixed with 4a6704f
